version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: gdash-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gdash
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./packages/database/init:/docker-entrypoint-initdb.d
      - ./packages/database/config/postgresql.conf:/etc/postgresql/postgresql.conf
