services:
  # Planetscale
  # ref1: https://github.com/prisma/prisma-engines/blob/976a00ae3c30ab9507fa742986c9c6f5327ba10f/docker-compose.yml
  # ref2: https://github.com/prisma/prisma/blob/ce6b54a9f77f966062f57870bd5f12d9941c9b88/docker/docker-compose.yml#L35C1-L55C36
  vitess-8:
    image: vitess/vttestserver:mysql80@sha256:64fb0a0e8a6d747f2c6cfab375413cd4c1defc0d03796bc40424878ab4ce9bf8
    restart: always
    ports:
      - 33807:33807
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h127.0.0.1', '-P33577']
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 25s
    environment:
      PORT: '33804' # unused in testing, but required by vttestserver
      KEYSPACES: 'unsharded' # unused in testing, but required by vttestserver
      NUM_SHARDS: '1' # unused in testing, but required by vttestserver
      MYSQL_BIND_HOST: '0.0.0.0'
      FOREIGN_KEY_MODE: 'disallow'
      MYSQL_MAX_CONNECTIONS: 100000
      TABLET_REFRESH_INTERVAL: '1s'
