name: Monorepo test
on: push
env:
  CACHE_VERSION: 2

jobs:
  test:
    runs-on: ubuntu-latest
    environment: CI
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: node setup (via volta)
        uses: volta-cli/action@v4

      - name: Install all packages
        run: yarn install --immutable

      - name: Turborepo Cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key:
            turbo/${{ env.CACHE_VERSION }}/${{ github.job }}/${{ github.ref_name }}/${{ github.sha }}
          restore-keys: |
            turbo/${{ env.CACHE_VERSION }}/${{ github.job }}/${{ github.ref_name }}/
            turbo/${{ env.CACHE_VERSION }}/${{ github.job }}/

      - name: Format check
        run: yarn format:check

      - name: Lint check
        run: yarn lint:ci

      - name: Build check
        run: yarn build:ci

      - name: Type check
        run: yarn typecheck

#      - name: Test
#        run: yarn test
