name: Monorepo test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    environment: CI
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          # cache: 'yarn' // temporary disabled for speed up (cache save time is too long)

      - name: Install all packages
        run: yarn install --immutable

      - name: Turborepo Cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
            turbo-${{ github.job }}-

      - name: Lint check
        run: yarn build

      - name: Build check
        run: yarn build

#      - name: Type check
#        run: yarn typecheck

#      - name: Test
#        run: yarn test
